GET http://localhost:8080/articles/5 HTTP/1.1

###

GET http://localhost:8080/magazines/1

###

GET http://localhost:8080/articles?issueNumber=1

###

GET http://localhost:8080/articles/not-a-number HTTP/1.1

###

POST http://localhost:8080/magazines HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "issueNumber": 1,
    "publishDate": 1743324397,
}

###

POST http://localhost:8080/series HTTP/1.1
content-type: application/json

{
    "title": "sample series",
    "description": "test series",
}

###

POST http://localhost:8080/articles HTTP/1.1
content-type: application/json

{
    "title": "sample article",
    "magazineId": 1,
    "order": 100,
    "seriesId": 1,
    "content": "# Test\nTest Content",
    "contentType": "MD",
    "accessibleLevel": 1
}
