@baseUrl = https://127.0.0.1.nip.io:4443
# @baseUrl = https://localhost:4443
# @baseUrl = http://localhost:8080

GET {{baseUrl}}/articles/5 HTTP/1.1

###

GET {{baseUrl}}/magazines/1

###

GET {{baseUrl}}/articles?issueNumber=1

###

GET {{baseUrl}}/articles/not-a-number HTTP/1.1

###

POST {{baseUrl}}/magazines HTTP/1.1
content-type: application/json

{
    "title": "sample",
    "issueNumber": 1,
    "publishDate": 1743324397,
}

###

POST {{baseUrl}}/series HTTP/1.1
content-type: application/json

{
    "title": "sample series",
    "description": "test series",
}

###

POST {{baseUrl}}/articles HTTP/1.1
content-type: application/json

{
    "title": "sample article",
    "magazineId": 1,
    "order": 100,
    "seriesId": 1,
    "content": "# Test\nTest Content",
    "contentType": "MD",
    "accessibleLevel": 1
}
